---
- name: copy {{ project | title }} configuration
  become: yes
  template:
    src: "{{ project }}.yml"
    dest: "{{ conf_dir }}/{{ project }}.yml"
  notify: restart {{ project }}

- name: copy Java options
  become: yes
  template:
    src: jvm.options
    dest: "{{ conf_dir }}/jvm.options"
  notify: restart {{ project }}

# Run tasks specific for the project if exists
- stat:
    path: project-specific.yml
  register: project_specific_file

- import_tasks: project-specific.yml
  when:
    project_specific_file.stat.exists
