# Check for mandatory parameters
- fail: msg="ls_instance_name must be specified and cannot be blank"
  when: ls_instance_name is not defined or ls_instance_name == ''

- fail: msg="ls_proxy_port must be specified and cannot be blank when ls_proxy_host is defined"
  when: (ls_proxy_port is not defined or ls_proxy_port == '') and (ls_proxy_host is defined and ls_proxy_host != '')

- debug: msg="File {{ item }}"
  with_fileglob:
   - "{{ ls_filter_fileglob }}"

- set_fact: conf_exist=true
  with_fileglob:
   - "{{ ls_filter_fileglob }}"
  when: not conf_exist

- fail: msg="At least one config file must exist, put some config file to path {{ ls_filter_fileglob | dirname }}/ (path can be set by ls_conf_fileglob)"
  when: not conf_exist

# Use systemd for the following distributions:
#   Ubuntu 15 and up
#   Debian 8 and up
#   Centos 7 and up
# Relies on logstash distribution installing a serviced script to determine whether one should be copied.
- set_fact: use_system_d={{ (ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('8', '>=')) or (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version | version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15', '>=')) }}

- fail: msg="Host must use systemd!"
  when: not use_system_d

- set_fact: instance_default_file={{ default_file | dirname }}/{{ ls_instance_name }}_{{ default_file | basename}}
- set_fact: conf_dir={{ ls_conf_dir }}/{{ ls_instance_name }}
- set_fact: instance_init_script={{ init_script | dirname }}/{{ ls_instance_name }}_{{ init_script | basename }}

- set_fact: instance_sysd_script={{ sysd_script | dirname }}/{{ ls_instance_name }}_{{ sysd_script | basename }}
  when: use_system_d

# For directories we also use the {{ inventory_hostname }}-{{ ls_instance_name }} - this helps if we have a shared SAN.
- set_fact: instance_suffix={{ inventory_hostname}}-{{ ls_instance_name }}
- set_fact: pid_dir={{ ls_pid_dir }}/{{ instance_suffix }}
- set_fact: log_dir={{ ls_log_dir }}/{{ instance_suffix }}
- set_fact: data_dir={{ ls_data_dir }}/{{ instance_suffix }}
- set_fact: patterns_dir={{ conf_dir }}/patterns
