---
- name: Ensure libselinux-python on CentOS 6.x
  become: yes
  yum: name=libselinux-python state=present update_cache=yes
  when: ( ansible_distribution == "CentOS" ) and ( ansible_distribution_major_version == "6" )

- name: RedHat - add Elastic repo
  become: yes
  template: src=elastic.repo dest=/etc/yum.repos.d/elastic-{{ elastic_major_version }}.repo
  when: ls_use_repository

- name: RedHat - include versionlock
  import_tasks: logstash-RedHat-version-lock.yml
  when: ls_version_lock

###
# 'until' loop works weird in ansible 2.5.0, it reports failed even if package was successfully installed/upgraded
###
- name: RedHat - Install Logstash
  become: yes
  yum: name=logstash{% if elastic_version is defined and elastic_version != ""  %}-{{ elastic_version }}{% endif %} state=present update_cache=yes
  when: ls_use_repository
  register: redhat_logstash_install_from_repo
  notify: restart logstash
  #until: redhat_logstash_install_from_repo.rc == 0
  #retries: 5
  #delay: 10

- name: RedHat - Install Logstash from url
  become: yes
  yum: name={% if ls_custom_package_url is defined %}{{ ls_custom_package_url }}{% else %}{{ ls_package_url }}-{{ ls_version }}.noarch.rpm{% endif %} state=present
  when: not ls_use_repository
  register: logstash_install_from_package
  notify: restart logstash
