---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always

- name: check-set-parameters
  import_tasks: logstash-parameters.yml
  tags:
      - always

- import_tasks: java.yml
  when: ls_java_install
  tags:
      - java

- import_tasks: logstash.yml
  tags:
      - install

- import_tasks: logstash-config.yml
  tags:
      - config

- import_tasks: logstash-grok-patterns.yml
  tags:
      - patterns

#- import_tasks: logstash-plugins.yml
#  when: ls_plugins is defined or ls_plugins_reinstall
#  tags:
#      - plugins

# We always execute xpack as we may need to remove features
- import_tasks: xpack/logstash-xpack.yml
  tags:
      - xpack

- meta: flush_handlers

- name: Make sure Logstash is started
  service: name={{ instance_init_script | basename }} state=started enabled=yes
  when: ls_start_service
