---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always

- name: check-set-parameters
  import_tasks: logstash-parameters.yml
  tags:
      - always

- import_tasks: java.yml
  when: ls_java_install
  tags:
      - java

- import_tasks: logstash.yml
  tags:
      - install

- import_tasks: logstash-config.yml
  tags:
      - config

- import_tasks: logstash-grok-patterns.yml
  tags:
      - patterns

#- import_tasks: logstash-plugins.yml
#  when: ls_plugins is defined or ls_plugins_reinstall
#  tags:
#      - plugins

# We always execute xpack as we may need to remove features
- import_tasks: xpack/logstash-xpack.yml
  tags:
      - xpack

- meta: flush_handlers

- name: Make sure Logstash is started
  service: name={{ instance_init_script | basename }} state=started enabled=yes
  when: ls_start_service

- name: Wait for Logstash to startup
  wait_for: host={{ ls_api_host }} port={{ ls_api_port }} delay=5 connect_timeout=1
  when: ls_restarted is defined and ls_restarted.changed and ls_start_service

- set_fact: manage_native_realm=false

- set_fact: manage_native_realm=true
  when: ls_start_service and ls_enable_xpack and ((ls_users is defined and ls_users.native is defined) or (ls_roles is defined and ls_roles.native is defined))

# If playbook runs too fast, Native commands could fail as the Native Realm is not yet up
- name: Wait 15 seconds for the Native Realm to come up
  pause: seconds=15
  when: manage_native_realm

