---
# ---
- import_tasks: variables.yml

- name: check supported OS
  fail:
    msg: "The system {{ ansible_os_family }} is not supported"
  when: ansible_os_family != "RedHat"

- set_fact:
    config: "{{ default_config }}"
  when: config is not defined

- set_fact:
    config: "{{ default_config | combine(config) }}"
  when: config is defined

# Run tasks specific for the project if exists
- local_action: stat path={{ role_path }}/tasks/prepare-specific.yml
  register: prepare_specific_file

- import_tasks: prepare-specific.yml
  when: prepare_specific_file.stat.exists
