
- name: reload systemd configuration
  become: yes
  command: systemctl daemon-reload

# Restart service and ensure it is enabled
- name: restart logstash
  become: yes
  service: name={{instance_init_script | basename}} state=restarted enabled=yes
  when:
    - ls_restart_on_change
    - ls_start_service
  register: ls_restarted

- name: iptables save
  command: service iptables save
